version: '2'

services:
  hello-container:
    image: realpage/alpine-bash:3.3

    volumes:
      - ./scripts:/home/scripts

    command: /bin/bash /home/scripts/welcome-compose.sh

  data-container:
    image: alpine:3.3

    volumes:
      - ./scripts:/home/scripts

    command: /bin/ash
